[package]
name = "ac-2"
version = "0.1.0"
authors = ["Chris Rose <offline@offby1.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
